spring:
  application:
    name: myboots-adminserver
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      # Eureka注册中心连接地址
      # 如果注册中心地址配置的域名，这里使用 http://域名/eureka/ 格式
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8088
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      uri: http://locahost:8888
#      name: application-zuul
##      profile: dev