spring:
  application:
    name: knife4j-server
server:
  port: 8001
swagger:
  markdowns: classpath:markdown/*.md
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/