spring:
  profiles:
    active: native
  cloud:
    config:
      uri: http://locahost:8888
      name: application-zuul
      profile: dev
  application:
    name: eureka-server
  zipkin:
      base-url: http://localhost:9411
  boot:
    admin:
      client:
        url: http://localhost:8088
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/